
## Step 1:First read in activity names and their measures we need 
## for merging purpose later.
variables=read.table("./UCI HAR Dataset/features.txt",sep="")
activity=read.table("./UCI HAR Dataset/activity_labels.txt",sep="")

## Next,read in Test set data,subjects,activity 
## name codes and all dimensions of activity measured.
testsubject=read.table("./UCI HAR Dataset/test/subject_test.txt"
                       ,sep="",col.names="Subject")
xtest=read.table("./UCI HAR Dataset/test/X_test.txt",sep=""
                 ,col.names=variables[,2])
ytest=read.table("./UCI HAR Dataset/test/Y_test.txt",sep=""
                 ,col.names="Activity")
## Extracts from activity dimensions(i.e.561 dimensions) only the 
## measures on mean or standard deviation for each variable.
meanvar1=grep("mean",names(xtest)); stdvar1=grep("std",names(xtest))
xtest1=xtest[,meanvar1]; xtest2=xtest[,stdvar1]
## Merge subjects,activity name codes and activity dimensions
## which are measures on mean or SD into one test set.
Test=cbind(testsubject,ytest,xtest1,xtest2)

## Read in Train set data as Step 2.
## read in Test set data,subjects,activity name codes and all 
## dimensions of activity measured.
trainsubject=read.table("./UCI HAR Dataset/train/subject_train.txt"
                        ,sep="",col.names="Subject")
xtrain=read.table("./UCI HAR Dataset/train/X_train.txt",sep=""
                  ,col.names=variables[,2])
ytrain=read.table("./UCI HAR Dataset/train/Y_train.txt",sep=""
                  ,col.names="Activity")
## Extracts from activity dimensions(i.e.561 dimensions) only the 
## measures on mean or standard deviation for each variable.
meanvar2=grep("mean",names(xtrain));stdvar2=grep("std"
                                                 ,names(xtrain))
xtrain1=xtrain[,meanvar2];xtrain2=xtrain[,stdvar2]
## Merge subjects,activity name codes and activity dimensions
## which are measures on mean or SD into one test set.
Train=cbind(trainsubject,ytrain,xtrain1,xtrain2)

## Merge test set and train set to form a complete data set.
TestTrain=rbind(Test,Train)
   

## Step 3:Uses descriptive activity names to name the activities
##       in the data set
TestTrain$Activity=factor(TestTrain$Activity,levels=activity[,1]
                          ,labels=activity[,2])
   
## Step 4:Appropriately labels the data set with descriptive 
## variable names. 
tobereplaced=tolower(names(TestTrain))
tobereplaced=gsub("\\.","",tobereplaced)
variables$lower=tolower(variables[,2])
variables$lower=gsub("-","",variables$lower)
variables$lower=sub("\\()","",variables$lower)
variables=variables[variables$lower%in%tobereplaced,]
variables$V2=as.character(variables$V2)
tobereplaced=c(c("Subject","Activity"),variables[,2])
colnames(TestTrain)=tobereplaced
## Creates a second, independent tidy data set with the average 
## of each variable for each activity and each subject.
group=list(TestTrain$Subject,TestTrain$Activity)
tidydata=aggregate(TestTrain,group,mean)
tidydata$Subject=tidydata$Activity=NULL
colnames(tidydata)=tobereplaced
## Final step: write out the data generated by above procedure.
write.table(tidydata,file="tidydata.txt",row.names=F)